# messaging_app/chats/serializers.py

from rest_framework import serializers
from .models import User, Conversation, Message

class UserSerializer(serializers.ModelSerializer):
    """
    Serializer for the custom User model.
    Includes essential user details like user_id, username, email, first_name, and last_name.
    """
    class Meta:
        model = User
        fields = ['user_id', 'username', 'email', 'first_name', 'last_name']
        read_only_fields = ['user_id'] # user_id is an auto-generated UUID and should not be set by the client

class MessageSerializer(serializers.ModelSerializer):
    """
    Serializer for the Message model.
    Includes nested sender details for read operations, providing a richer representation
    of who sent the message.
    """
    # This creates a nested representation of the sender object.
    sender = UserSerializer(read_only=True)

    class Meta:
        model = Message
        # Fields to include in the serialized output.
        # 'conversation' is included as a primary key field for associating messages with conversations.
        fields = ['message_id', 'sender', 'conversation', 'message_body', 'sent_at', 'is_read']
        # Fields that are automatically generated by the model and should not be set by the client.
        read_only_fields = ['message_id', 'sent_at']

class ConversationSerializer(serializers.ModelSerializer):
    """
    Serializer for the Conversation model.
    Handles nested relationships for participants and messages, allowing a complete
    view of a conversation including its members and all messages within it.
    """
   
    participants = UserSerializer(many=True, read_only=True)

    
    messages = MessageSerializer(many=True, read_only=True)

    class Meta:
        model = Conversation
        # Fields to include in the serialized output.
        fields = ['conversation_id', 'participants', 'messages', 'created_at', 'updated_at']
        # Fields that are automatically generated by the model and should not be set by the client.
        read_only_fields = ['conversation_id', 'created_at', 'updated_at']

    